-- CreateEnum
CREATE TYPE "GamePhase" AS ENUM ('FARMING', 'FIGHTING');

-- AlterTable
ALTER TABLE "GameSession" ADD COLUMN     "currentRound" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "phase" "GamePhase" NOT NULL DEFAULT 'FARMING',
ADD COLUMN     "player1Ready" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "player1Wins" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "player2Ready" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "player2Wins" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "gold" SET DEFAULT 500;
